FROM python:3.8
WORKDIR /app
RUN pip install pandas scikit-learn streamlit
COPY . /app/
ENTRYPOINT [ "streamlit","run","app.py" ]
# ENTRYPOINT [ "streamlit","run","app.py", "--server.port=8501", "--server.address=0.0.0.0" ]
# cambiar en la url por localhost:8501